# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'
linters:
  default: none
  enable:
    # all
    - asciicheck
    - bidichk
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - inamedparam
    - iotamixing
    - ireturn
    - maintidx
    - makezero
    - mirror
    - modernize
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - recvcheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # encoding/json
    - errchkjson
  settings:
    embeddedstructfieldcheck:
      forbid-mutex: true
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocritic:
      enable-all: true
      disabled-checks:
        - builtinShadow
    godoclint:
      default: all
    nolintlint:
      require-specific: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - godoclint
        text: 'symbol should have a godoc'
      - path: _test\.go
        linters:
          - exhaustruct
        text: 'is missing field'
      - path: _test\.go
        linters:
          - dupl
        text: 'lines are duplicate of'
      - path: _test\.go
        linters:
          - funlen
        text: 'is too long'
      - path: _test\.go
        linters:
          - gosec
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      extra-rules: true
