# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# yamllint disable rule:empty-lines
version: '3'

output: prefixed

tasks:
  lint:
    desc: Run all linters (Go, YAML, MD, etc.)
    deps:
      - lint:go
      - lint:yml
      - lint:md
      - lint:reuse
      - lint:typos

  lint:go:
    desc: Check Go code quality
    cmd: golangci-lint run ./...

  lint:yml:
    desc: Validate YAML syntax
    cmd: yamllint --strict .

  lint:md:
    desc: Check Markdown formatting
    cmd: markdownlint-cli2 **/*.md

  lint:reuse:
    desc: Verify license compliance
    cmd: reuse lint

  lint:typos:
    desc: Check for common misspellings
    cmd: typos

  test:
    desc: Run unit tests with race detector
    cmd: go test -v -race -cover ./...

  build:
    desc: Compile the tgen binary
    cmd: go build -o tgen ./cmd/tgen

  run:
    desc: Run tgen locally
    cmd: go run ./cmd/tgen

  release:patch:
    desc: Release a new patch version (x.x.+1)
    cmds:
      - task: release
        vars: { NEXT: { sh: svu patch } }

  release:minor:
    desc: Release a new minor version (x.+1.0)
    cmds:
      - task: release
        vars: { NEXT: { sh: svu minor } }

  release:major:
    desc: Release a new major version (+1.0.0)
    cmds:
      - task: release
        vars: { NEXT: { sh: svu major } }

  release:
    internal: true
    preconditions:
      - sh: '[ $(git symbolic-ref --short HEAD) = "main" ]'
        msg: "Not on main branch"
      - sh: '[ -z "$(git status --porcelain)" ]'
        msg: "Git is dirty"
      - sh: 'git fetch --tags && [ $(git rev-parse HEAD) = $(git rev-parse @{u}) ]'
        msg: "Not synced with origin"
    deps:
      - build
      - test
    prompt: "This will release {{.NEXT}}. Continue?"
    cmds:
      - git tag {{.NEXT}}
      - git push origin {{.NEXT}}
      - echo "Released {{.NEXT}}"

  release:check:
    desc: Dry-run GoReleaser to verify configuration
    cmds:
      - goreleaser check
      - goreleaser release --snapshot --clean