# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# yamllint disable rule:empty-lines
version: '3'

output: prefixed

tasks:
  lint:
    deps:
      - lint:go
      - lint:yml
      - lint:md
      - lint:reuse
      - lint:typos

  lint:go:
    cmd: golangci-lint run ./...

  lint:yml:
    cmd: yamllint --strict .

  lint:md:
    cmd: markdownlint-cli2 **/*.md

  lint:reuse:
    cmd: reuse lint

  lint:typos:
    cmd: typos

  test:
    cmd: go test -v -race -cover ./...

  build:
    cmd: go build -o tgen cmd/tgen/main.go

  run:
    cmd: go run cmd/tgen/main.go
