 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated 2026-05-17 from Telegram Bot API 10.0
# See release notes https://core.telegram.org/bots/api#may-8-2026

from .client import Connection, FakeConnection, HTTPConnection, Error
from .methods import *