 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated from Telegram Bot API 10.1
# See release notes https://core.telegram.org/bots/api#june-11-2026

from .client import Connection, FakeConnection, HTTPConnection, Error
from .methods import *