 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated 2026-05-18 from Telegram Bot API 10.0
# See release notes https://core.telegram.org/bots/api#may-8-2026

from __future__ import annotations

from typing import Protocol

import httpx
from pydantic import TypeAdapter

from ..client import (
    Call,
    CallQueue,
    Envelope,
    Error,
    Payload,
    Response,
    T,
)
from ..method import Method


class Connection(Protocol):
    async def do(self, method: Method, payload: Payload, adapter: TypeAdapter[T]) -> T: ...


class HTTPConnection:
    def __init__(self, client: httpx.AsyncClient, token: str) -> None:
        self._client = client
        self._token = token

    async def do(self, method: Method, payload: Payload, adapter: TypeAdapter[T]) -> T:
        req = payload.request("POST", f"https://api.telegram.org/bot{self._token}/{method.value}")
        resp = await self._client.send(req)
        envelope = Envelope.model_validate(resp.json())
        if not envelope.ok:
            raise Error(envelope.error_code, envelope.description, envelope.parameters)
        return adapter.validate_python(envelope.result)


class FakeConnection:
    def __init__(self, queue: CallQueue) -> None:
        self._queue = queue

    async def do(self, method: Method, _: Payload, adapter: TypeAdapter[T]) -> T:
        try:
            call = self._queue.next()
        except RuntimeError as e:
            raise RuntimeError(f"FakeConnection: call to {method!r}: {e}") from e
        if call.method != method:
            raise RuntimeError(f"FakeConnection: expected {call.method!r}, got {method!r}")
        match call.response:
            case Exception() as exc:
                raise exc
            case value:
                raw = TypeAdapter(type(value)).dump_python(value, mode="json")
                return adapter.validate_python(raw)