# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
# yaml-language-server: $schema=https://mise.jdx.dev/schema/mise.json

[settings]
always_keep_download = false
legacy_version_file = false

[tools]
"go" = "1.26.2"
"github:caarlos0/svu" = "3.4.0"
"github:crate-ci/typos" = "1.46.0"
"github:golangci/golangci-lint" = "2.11.4"
"github:goreleaser/goreleaser" = "2.15.4"
"github:go-task/task" = "3.50.0"
"github:rhysd/actionlint" = "1.7.12"
"github:tamasfe/taplo" = "0.10.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.1.4"
"npm:markdownlint-cli2" = "0.22.1"
"pipx:reuse" = "6.2.0"
"pipx:yamllint" = "1.38.0"
