 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated 2026-05-22 from Telegram Bot API 10.0
# See release notes https://core.telegram.org/bots/api#may-8-2026

from .client import Connection, HTTPConnection, Error
from .method import Method
from .methods import *
from .types import *