 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated from Telegram Bot API 10.2
# See release notes https://core.telegram.org/bots/api#july-14-2026

from .client import Connection, HTTPConnection, Error
from .method import Method
from .methods import *
from .types import *