 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated from Telegram Bot API 10.1
# See release notes https://core.telegram.org/bots/api#june-11-2026

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, TypeVar

import httpx
from pydantic import BaseModel, TypeAdapter

from .method import Method
from .types import ResponseParameters

T = TypeVar("T")


class Payload(Protocol):
    """Carries the accumulated fields of an API method call and produces an HTTP
    request from them."""

    def request(self, method: str, url: str) -> httpx.Request: ...


class Connection(Protocol):
    """Executes Telegram Bot API methods over a transport."""

    def do(self, method: Method, payload: Payload, adapter: TypeAdapter[T]) -> T: ...


class _Envelope(BaseModel):
    """The Telegram Bot API JSON response wrapper."""

    ok: bool
    result: Any = None
    error_code: int = 0
    description: str = "<no description>"
    parameters: ResponseParameters | None = None


class Error(Exception):
    """A failure response from the Telegram Bot API."""

    def __init__(self, code: int, description: str, parameters: ResponseParameters | None = None) -> None:
        super().__init__(description)
        self.code = code
        self.description = description
        self.parameters = parameters


class HTTPConnection:
    """Implements Connection over HTTP using the Telegram Bot API endpoint."""

    def __init__(self, client: httpx.Client, token: str) -> None:
        self._client = client
        self._token = token

    def do(self, method: Method, payload: Payload, adapter: TypeAdapter[T]) -> T:
        """Sends a POST to the Telegram API and decodes the result.

        Raises Error if the API reports a failure.
        """
        req = payload.request("POST", f"https://api.telegram.org/bot{self._token}/{method.value}")
        resp = self._client.send(req)
        env = _Envelope.model_validate(resp.json())
        if not env.ok:
            raise Error(env.error_code, env.description, env.parameters)
        return adapter.validate_python(env.result)


type Response = Any | Exception
"""The outcome of a FakeConnection call: a value or an exception."""


@dataclass
class Call:
    """Pairs a Method with its canned Response for use in FakeConnection."""

    method: Method
    response: Response


class CallQueue(Protocol):
    """Yields canned calls for FakeConnection."""

    def next(self) -> Call: ...


class SeqCallQueue:
    """Implements CallQueue as a strict sequential list of Calls."""

    def __init__(self, *calls: Call) -> None:
        self._calls = list(calls)
        self._index = 0

    def next(self) -> Call:
        """Returns the next Call in the sequence, or raises RuntimeError if exhausted."""
        if self._index >= len(self._calls):
            raise RuntimeError("queue exhausted")
        call = self._calls[self._index]
        self._index += 1
        return call

    def calls(self) -> list[Call]:
        """Returns the calls consumed so far."""
        return self._calls[: self._index]


class FakeConnection:
    """Implements Connection with canned responses for use in tests.

    Misconfiguration raises RuntimeError rather than silently passing.
    """

    def __init__(self, queue: CallQueue) -> None:
        self._queue = queue

    def do(self, method: Method, _: Payload, adapter: TypeAdapter[T]) -> T:
        """Draws the next Call from the queue and returns its canned response.

        Raises RuntimeError if the queue is exhausted or the method does not match.
        """
        try:
            call = self._queue.next()
        except RuntimeError as e:
            raise RuntimeError(f"FakeConnection: call to {method!r}: {e}") from e
        if call.method != method:
            raise RuntimeError(f"FakeConnection: expected {call.method!r}, got {method!r}")
        match call.response:
            case Exception() as exc:
                raise exc
            case value:
                raw = TypeAdapter(type(value)).dump_python(value, mode="json")
                return adapter.validate_python(raw)