 
# Code generated by tgen (devel); DO NOT EDIT.
#
# Generated 2026-05-18 from Telegram Bot API 10.0
# See release notes https://core.telegram.org/bots/api#may-8-2026

import json
from collections.abc import Sequence
from typing import IO, Any, Protocol

import httpx
from pydantic import TypeAdapter


class MultipartPayload:
    def __init__(self) -> None:
        self._data: dict[str, str] = {}
        self._files: dict[str, tuple[str, IO[bytes]]] = {}
        self._counter: int = 0

    def text(self, key: str, value: str) -> None:
        self._data[key] = value

    def file(self, key: str, name: str, reader: IO[bytes]) -> None:
        self._files[key] = (name, reader)

    def attach_key(self) -> str:
        key = f"attachment_{self._counter}"
        self._counter += 1
        return key

    def request(self, method: str, url: str) -> httpx.Request:
        if not self._data and not self._files:
            return httpx.Request(method, url)
        return httpx.Request(method, url, data=self._data, files=self._files)


class Part(Protocol):
    def write(self, payload: MultipartPayload, key: str) -> None: ...


class StrPart:
    def __init__(self, value: str) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        payload.text(key, self._value)


class IntPart:
    def __init__(self, value: int) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        payload.text(key, str(self._value))


class FloatPart:
    def __init__(self, value: float) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        payload.text(key, str(self._value))


class BoolPart:
    def __init__(self, value: bool) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        payload.text(key, "true" if self._value else "false")


class ListPart:
    def __init__(self, value: Any) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        payload.text(key, TypeAdapter(type(self._value)).dump_json(self._value).decode())


class FormJSON(Protocol):
    def form_json(self, payload: MultipartPayload) -> str: ...


class ListFormJsonPart:
    def __init__(self, value: Sequence[FormJSON]) -> None:
        self._value = value

    def write(self, payload: MultipartPayload, key: str) -> None:
        items = [json.loads(item.form_json(payload)) for item in self._value]
        payload.text(key, json.dumps(items))