  
// Code generated by tgen (devel); DO NOT EDIT.
//
// Generated 2026-05-22 from Telegram Bot API 10.0
// See release notes https://core.telegram.org/bots/api#may-8-2026

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"strconv"
)

// Connection executes Telegram Bot API methods over a transport.
type Connection interface {
	// Do executes method with the given payload and decodes the API result into
	// response. It returns an error if the transport fails or if the API reports
	// a failure.
	Do(ctx context.Context, method Method, payload Payload, response any) error
}

// Payload carries the accumulated fields of an API method call and produces an
// HTTP request from them.
type Payload interface {
	Request(ctx context.Context, method, url string) (*http.Request, error)
}

// HTTPConnection implements Connection over HTTP using the Telegram Bot API
// endpoint.
type HTTPConnection struct {
	client *http.Client
	token  string
}

// NewHTTPConnection creates an HTTPConnection from an HTTP client and a bot
// token.
func NewHTTPConnection(client *http.Client, token string) HTTPConnection {
	return HTTPConnection{client: client, token: token}
}

// Do sends a multipart/form-data POST to the Telegram API and decodes the
// result into response. It returns an error if the request cannot be built,
// the transport fails, the API reports a failure, or the result cannot be
// decoded.
func (c HTTPConnection) Do(
	ctx context.Context,
	method Method,
	payload Payload,
	response any,
) error {
	req, err := payload.Request(ctx, http.MethodPost, c.url(method))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("sending request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	var env envelope
	if err = json.NewDecoder(resp.Body).Decode(&env); err != nil {
		return fmt.Errorf("decoding envelope: %w", err)
	}
	if !env.Ok {
		code := 0
		if env.ErrorCode != nil {
			code = *env.ErrorCode
		}
		desc := "<no description>"
		if env.Description != nil {
			desc = *env.Description
		}
		return &Error{Code: code, Description: desc, Parameters: env.Parameters}
	}
	if err = json.Unmarshal(env.Result, response); err != nil {
		return fmt.Errorf("decoding result: %w", err)
	}
	return nil
}

func (c HTTPConnection) url(method Method) string {
	return fmt.Sprintf("https://api.telegram.org/bot%s/%s", c.token, method)
}

// envelope is the Telegram Bot API JSON response wrapper.
type envelope struct {
	Ok          bool                `json:"ok"`
	Result      json.RawMessage     `json:"result,omitempty"`
	ErrorCode   *int                `json:"error_code,omitempty"`
	Description *string             `json:"description,omitempty"`
	Parameters  *ResponseParameters `json:"parameters,omitempty"`
}

// Error represents a failure response from the Telegram Bot API.
type Error struct {
	Code        int
	Description string
	Parameters  *ResponseParameters
}

// Error returns a string combining the error code and description.
func (e *Error) Error() string {
	return fmt.Sprintf("telegram %d: %s", e.Code, e.Description)
}

// Response represents the outcome of a FakeConnection call — either a value or
// an error.
//sumtype:decl
type Response interface{ sealedResponse() }

type okResponse struct{ value any }
type errResponse struct{ err error }

func (okResponse) sealedResponse()  {}
func (errResponse) sealedResponse() {}

// Ok creates a Response that returns v as the decoded result.
func Ok(v any) Response { return okResponse{value: v} }

// Err creates a Response that returns e as the method error.
func Err(e error) Response { return errResponse{err: e} }

// Call pairs a Method with its canned Response for use in FakeConnection.
type Call struct {
	method   Method
	response Response
}

// NewCall constructs a Call from method and response.
func NewCall(method Method, response Response) Call {
	return Call{method: method, response: response}
}

// Method returns the API method name.
func (c Call) Method() Method { return c.method }

// Response returns the canned response.
func (c Call) Response() Response { return c.response }

// CallQueue yields canned calls for FakeConnection.
type CallQueue interface {
	Next() (Call, error)
}

// SeqCallQueue implements CallQueue as a strict sequential list of Calls.
type SeqCallQueue struct {
	calls []Call
	index int
}

// NewSeqCallQueue creates a SeqCallQueue from the given calls.
func NewSeqCallQueue(calls ...Call) *SeqCallQueue {
	return &SeqCallQueue{calls: calls}
}

// Next returns the next Call in the sequence, or an error if the queue is exhausted.
func (q *SeqCallQueue) Next() (Call, error) {
	if q.index >= len(q.calls) {
		return Call{}, errors.New("queue exhausted")
	}
	call := q.calls[q.index]
	q.index++
	return call, nil
}

// Calls returns the calls consumed so far.
func (q *SeqCallQueue) Calls() []Call {
	return q.calls[:q.index]
}

// FakeConnection implements Connection with canned responses for use in tests.
// Misconfiguration causes a panic rather than an error to prevent silent test
// failures.
type FakeConnection struct {
	queue CallQueue
}

// NewFakeConnection creates a FakeConnection that draws responses from queue.
func NewFakeConnection(queue CallQueue) FakeConnection {
	return FakeConnection{queue: queue}
}

// Do draws the next Call from the queue and returns its canned response. It
// panics if the queue is exhausted, the next call's Method does not match
// method, or the canned value cannot be decoded into response.
func (c FakeConnection) Do(_ context.Context, method Method, _ Payload, response any) error {
	call, err := c.queue.Next()
	if err != nil {
		panic(fmt.Sprintf("FakeConnection: call to %q: %v", method, err))
	}
	if call.Method() != method {
		panic(fmt.Sprintf("FakeConnection: expected %q, got %q", call.Method(), method))
	}
	switch resp := call.Response().(type) {
	case errResponse:
		return resp.err
	case okResponse:
		data, err := json.Marshal(resp.value)
		if err != nil {
			panic(fmt.Sprintf("FakeConnection: marshaling response for %q: %v", method, err))
		}
		if err = json.Unmarshal(data, response); err != nil {
			panic(fmt.Sprintf("FakeConnection: unmarshaling response for %q: %v", method, err))
		}
		return nil
	default:
		panic(fmt.Sprintf("FakeConnection: unknown response type %T for %q", call.Response(), method))
	}
}

// multipartPayload accumulates form fields and file parts, then builds the
// HTTP request body.
type multipartPayload struct {
	buffer   *bytes.Buffer
	writer   *multipart.Writer
	counter  int
	modified bool
}

func newMultipartPayload() *multipartPayload {
	b := &bytes.Buffer{}
	return &multipartPayload{buffer: b, writer: multipart.NewWriter(b)}
}

// attachKey returns a unique key for the next file attachment.
func (m *multipartPayload) attachKey() string {
	key := fmt.Sprintf("attachment_%d", m.counter)
	m.counter++
	return key
}

// text adds a plain-text form field.
func (m *multipartPayload) text(key, value string) error {
	m.modified = true
	return m.writer.WriteField(key, value)
}

// file adds a binary file form part.
func (m *multipartPayload) file(key, name string, reader io.Reader) error {
	m.modified = true
	part, err := m.writer.CreateFormFile(key, name)
	if err != nil {
		return fmt.Errorf("creating file part: %w", err)
	}
	if _, err = io.Copy(part, reader); err != nil {
		return fmt.Errorf("copying file: %w", err)
	}
	return nil
}

func (m *multipartPayload) Request(ctx context.Context, method, url string) (*http.Request, error) {
	if err := m.writer.Close(); err != nil {
		return nil, fmt.Errorf("closing multipart: %w", err)
	}
	if !m.modified {
		return http.NewRequestWithContext(ctx, method, url, http.NoBody)
	}
	req, err := http.NewRequestWithContext(ctx, method, url, m.buffer)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", m.writer.FormDataContentType())
	return req, nil
}

// part writes a value into a multipart form at the given key.
type part interface {
	write(p *multipartPayload, key string) error
}

// formJSON serializes a value to JSON, registering any file uploads in p as
// side effects.
type formJSON interface {
	json(p *multipartPayload) ([]byte, error)
}

// stringPart writes a string value as a plain-text form field.
type stringPart struct {
	v string
}

func newStringPart[T ~string](v T) stringPart {
	return stringPart{v: string(v)}
}

func (s stringPart) write(p *multipartPayload, key string) error {
	return p.text(key, s.v)
}

// int64Part writes an int64 value as a decimal plain-text form field.
type int64Part struct {
	v int64
}

func newInt64Part[T ~int64](v T) int64Part {
	return int64Part{v: int64(v)}
}

func (i int64Part) write(p *multipartPayload, key string) error {
	return p.text(key, strconv.FormatInt(i.v, 10))
}

// float64Part writes a float64 value as a decimal plain-text form field.
type float64Part struct {
	v float64
}

func newFloat64Part[T ~float64](v T) float64Part {
	return float64Part{v: float64(v)}
}

func (f float64Part) write(p *multipartPayload, key string) error {
	return p.text(key, strconv.FormatFloat(f.v, 'f', -1, 64))
}

// boolPart writes a bool value as a plain-text form field.
type boolPart struct {
	v bool
}

func newBoolPart[T ~bool](v T) boolPart {
	return boolPart{v: bool(v)}
}

func (b boolPart) write(p *multipartPayload, key string) error {
	return p.text(key, strconv.FormatBool(b.v))
}

// primitiveSlicePart writes a slice of primitive values as a JSON-encoded
// plain-text form field, without file resolution.
type primitiveSlicePart[T any] struct {
	v T
}

func newPrimitiveSlicePart[T any](v T) primitiveSlicePart[T] {
	return primitiveSlicePart[T]{v: v}
}

func (j primitiveSlicePart[T]) write(p *multipartPayload, key string) error {
	data, err := json.Marshal(j.v)
	if err != nil {
		return err
	}
	return p.text(key, string(data))
}

// objectSlicePart writes a slice of formJSON values as a JSON-encoded
// plain-text form field, resolving file attachments in each element.
type objectSlicePart[T formJSON] struct {
	v []T
}

func newObjectSlicePart[T formJSON](v []T) objectSlicePart[T] {
	return objectSlicePart[T]{v: v}
}

func (s objectSlicePart[T]) write(p *multipartPayload, key string) error {
	parts := make([]json.RawMessage, len(s.v))
	for i, el := range s.v {
		data, err := el.json(p)
		if err != nil {
			return err
		}
		parts[i] = data
	}
	data, err := json.Marshal(parts)
	if err != nil {
		return err
	}
	return p.text(key, string(data))
}