  
// Code generated by tgen (devel); DO NOT EDIT.
//
// Generated 2026-05-18 from Telegram Bot API 10.0
// See release notes https://core.telegram.org/bots/api#may-8-2026

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"strconv"
)

// Connection executes Telegram Bot API methods over a transport.
type Connection interface {
	// Do sends method with request as the JSON body and decodes the result into
	// response. It returns an error if the transport fails or the API reports a
	// failure.
	Do(ctx context.Context, method Method, payload Payload, response any) error
}

// HTTPConnection implements Connection over HTTP using the Telegram Bot API
// endpoint.
type HTTPConnection struct {
	client *http.Client
	token  string
}

// NewHTTPConnection creates an HTTPConnection from an HTTP client and a bot
// token.
func NewHTTPConnection(client *http.Client, token string) HTTPConnection {
	return HTTPConnection{client: client, token: token}
}

// Do sends a multipart/form-data POST to the Telegram API and decodes the
// result into response. It returns an error if the request cannot be built,
// the transport fails, the API reports a failure, or the result cannot be
// decoded.
func (c HTTPConnection) Do(
	ctx context.Context,
	method Method,
	payload Payload,
	response any,
) error {
	req, err := payload.Request(ctx, http.MethodPost, c.url(method))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("sending request: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	var envelope Envelope
	if err = json.NewDecoder(resp.Body).Decode(&envelope); err != nil {
		return fmt.Errorf("decoding envelope: %w", err)
	}
	if !envelope.Ok {
		code := 0
		if envelope.ErrorCode != nil {
			code = *envelope.ErrorCode
		}
		desc := "<no description>"
		if envelope.Description != nil {
			desc = *envelope.Description
		}
		return &Error{Code: code, Description: desc, Parameters: envelope.Parameters}
	}
	if err = json.Unmarshal(envelope.Result, response); err != nil {
		return fmt.Errorf("decoding result: %w", err)
	}
	return nil
}

func (c HTTPConnection) url(method Method) string {
	return fmt.Sprintf("https://api.telegram.org/bot%s/%s", c.token, method)
}

// Envelope represents the standard Telegram Bot API JSON response envelope.
type Envelope struct {
	Ok          bool                `json:"ok"`
	Result      json.RawMessage     `json:"result,omitempty"`
	ErrorCode   *int                `json:"error_code,omitempty"`
	Description *string             `json:"description,omitempty"`
	Parameters  *ResponseParameters `json:"parameters,omitempty"`
}

// Error represents a failure response from the Telegram Bot API.
type Error struct {
	Code        int
	Description string
	Parameters  *ResponseParameters
}

// Error returns a string combining the error code and description.
func (e *Error) Error() string {
	return fmt.Sprintf("telegram %d: %s", e.Code, e.Description)
}

// Response represents the outcome of a FakeConnection call — either a value or
// an error.
type Response struct {
	value any
	err   error
}

// Ok creates a Response that returns v as the decoded result.
func Ok(v any) Response {
	return Response{value: v, err: nil}
}

// Err creates a Response that returns e as the method error.
func Err(e error) Response {
	return Response{value: nil, err: e}
}

// Responses maps Method values to canned outcomes for FakeConnection.
type Responses map[Method]Response

// FakeConnection implements Connection with canned responses for use in tests.
// Misconfiguration causes a panic rather than an error to prevent silent test
// failures.
type FakeConnection struct {
	responses Responses
}

// NewFakeConnection creates a FakeConnection that returns the given canned
// responses.
func NewFakeConnection(r Responses) FakeConnection {
	return FakeConnection{responses: r}
}

// Do returns the canned error for method if the Response was created with Err,
// or populates response with the canned value. It panics if method was not
// registered in Responses or if the canned value cannot be decoded into
// response.
func (c FakeConnection) Do(_ context.Context, method Method, _ Payload, response any) error {
	resp, ok := c.responses[method]
	if !ok {
		panic(fmt.Sprintf("FakeConnection: unexpected method %q", method))
	}
	if resp.err != nil {
		return resp.err
	}
	data, err := json.Marshal(resp.value)
	if err != nil {
		panic(fmt.Sprintf("FakeConnection: marshaling response for %q: %v", method, err))
	}
	err = json.Unmarshal(data, response)
	if err != nil {
		panic(fmt.Sprintf("FakeConnection: unmarshaling response for %q: %v", method, err))
	}
	return nil
}

// Payload produces an HTTP request from accumulated method fields.
type Payload interface {
	Request(ctx context.Context, method, url string) (*http.Request, error)
}

// MultipartPayload builds a multipart/form-data request body.
type MultipartPayload struct {
	buffer   *bytes.Buffer
	writer   *multipart.Writer
	counter  int
	modified bool
}

// NewMultipartPayload creates an empty MultipartPayload.
func NewMultipartPayload() *MultipartPayload {
	b := &bytes.Buffer{}
	return &MultipartPayload{buffer: b, writer: multipart.NewWriter(b)}
}

func (m *MultipartPayload) AttachKey() string {
	key := fmt.Sprintf("attachment_%d", m.counter)
	m.counter++
	return key
}

// Text adds a plain-text form part.
func (m *MultipartPayload) Text(key, value string) error {
	m.modified = true
	return m.writer.WriteField(key, value)
}

// File adds a binary file form part.
func (m *MultipartPayload) File(key, name string, reader io.Reader) error {
	m.modified = true
	part, err := m.writer.CreateFormFile(key, name)
	if err != nil {
		return fmt.Errorf("creating file part: %w", err)
	}
	if _, err = io.Copy(part, reader); err != nil {
		return fmt.Errorf("copying file: %w", err)
	}
	return nil
}

func (m *MultipartPayload) Request(ctx context.Context, method, url string) (*http.Request, error) {
	if err := m.writer.Close(); err != nil {
		return nil, fmt.Errorf("closing multipart: %w", err)
	}
	if !m.modified {
		return http.NewRequestWithContext(ctx, method, url, http.NoBody)
	}
	req, err := http.NewRequestWithContext(ctx, method, url, m.buffer)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", m.writer.FormDataContentType())
	return req, nil
}

// Part writes a single method field into a Form.
type Part interface {
	Write(p *MultipartPayload, key string) error
}

// FormJSON encodes a value as JSON, resolving any InputFile references into p.
type FormJSON interface {
	JSON(p *MultipartPayload) ([]byte, error)
}

type StringPart struct {
	v string
}

func NewStringPart[T ~string](v T) StringPart {
	return StringPart{v: string(v)}
}

func (s StringPart) Write(p *MultipartPayload, key string) error {
	return p.Text(key, s.v)
}

type Int64Part struct {
	v int64
}

func NewInt64Part[T ~int64](v T) Int64Part {
	return Int64Part{v: int64(v)}
}

func (i Int64Part) Write(p *MultipartPayload, key string) error {
	return p.Text(key, strconv.FormatInt(i.v, 10))
}

type Float64Part struct {
	v float64
}

func NewFloat64Part[T ~float64](v T) Float64Part {
	return Float64Part{v: float64(v)}
}

func (f Float64Part) Write(p *MultipartPayload, key string) error {
	return p.Text(key, strconv.FormatFloat(f.v, 'f', -1, 64))
}

type BoolPart struct {
	v bool
}

func NewBoolPart[T ~bool](v T) BoolPart {
	return BoolPart{v: bool(v)}
}

func (b BoolPart) Write(p *MultipartPayload, key string) error {
	return p.Text(key, strconv.FormatBool(b.v))
}

type JSONPart[T any] struct {
	v T
}

func NewJSONPart[T any](v T) JSONPart[T] {
	return JSONPart[T]{v: v}
}

func (j JSONPart[T]) Write(p *MultipartPayload, key string) error {
	data, err := json.Marshal(j.v)
	if err != nil {
		return err
	}
	return p.Text(key, string(data))
}

type SlicePart[T FormJSON] struct {
	v []T
}

func NewSlicePart[T FormJSON](v []T) SlicePart[T] {
	return SlicePart[T]{v: v}
}

func (s SlicePart[T]) Write(p *MultipartPayload, key string) error {
	parts := make([]json.RawMessage, len(s.v))
	for i, el := range s.v {
		data, err := el.JSON(p)
		if err != nil {
			return err
		}
		parts[i] = data
	}
	data, err := json.Marshal(parts)
	if err != nil {
		return err
	}
	return p.Text(key, string(data))
}