  
// Code generated by tgen (devel); DO NOT EDIT.
//
// Generated 2026-05-19 from Telegram Bot API 10.0
// See release notes https://core.telegram.org/bots/api#may-8-2026

package api

import (
    "encoding/json"
    "fmt"
)  
// This object describes the origin of a message. It can be one of
//
// See https://core.telegram.org/bots/api#messageorigin
//sumtype:decl
type MessageOrigin interface{ part; formJSON; sealedMessageOrigin() }

func (v MessageOriginUser) sealedMessageOrigin() {}
func (v MessageOriginHiddenUser) sealedMessageOrigin() {}
func (v MessageOriginChat) sealedMessageOrigin() {}
func (v MessageOriginChannel) sealedMessageOrigin() {}

func unmarshalMessageOrigin(data []byte) (MessageOrigin, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "user":
		var v MessageOriginUser
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "hidden_user":
		var v MessageOriginHiddenUser
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat":
		var v MessageOriginChat
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "channel":
		var v MessageOriginChannel
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown MessageOrigin: %q", disc.Key)
	}
}  
// This object describes paid media. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#paidmedia
//sumtype:decl
type PaidMedia interface{ part; formJSON; sealedPaidMedia() }

func (v PaidMediaLivePhoto) sealedPaidMedia() {}
func (v PaidMediaPhoto) sealedPaidMedia() {}
func (v PaidMediaPreview) sealedPaidMedia() {}
func (v PaidMediaVideo) sealedPaidMedia() {}

func unmarshalPaidMedia(data []byte) (PaidMedia, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "live_photo":
		var v PaidMediaLivePhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "photo":
		var v PaidMediaPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "preview":
		var v PaidMediaPreview
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v PaidMediaVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown PaidMedia: %q", disc.Key)
	}
}  
// This object represents the content of a poll description or a quiz
// explanation to be sent. It should be one of
//
// See https://core.telegram.org/bots/api#inputpollmedia
//sumtype:decl
type InputPollMedia interface{ part; formJSON; sealedInputPollMedia() }

func (v InputMediaAnimation) sealedInputPollMedia() {}
func (v InputMediaAudio) sealedInputPollMedia() {}
func (v InputMediaDocument) sealedInputPollMedia() {}
func (v InputMediaLivePhoto) sealedInputPollMedia() {}
func (v InputMediaLocation) sealedInputPollMedia() {}
func (v InputMediaPhoto) sealedInputPollMedia() {}
func (v InputMediaVenue) sealedInputPollMedia() {}
func (v InputMediaVideo) sealedInputPollMedia() {}

func unmarshalInputPollMedia(data []byte) (InputPollMedia, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "animation":
		var v InputMediaAnimation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "audio":
		var v InputMediaAudio
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "document":
		var v InputMediaDocument
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "live_photo":
		var v InputMediaLivePhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "location":
		var v InputMediaLocation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "photo":
		var v InputMediaPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "venue":
		var v InputMediaVenue
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v InputMediaVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputPollMedia: %q", disc.Key)
	}
}  
// This object represents the content of a poll option to be sent. It should be
// one of
//
// See https://core.telegram.org/bots/api#inputpolloptionmedia
//sumtype:decl
type InputPollOptionMedia interface{ part; formJSON; sealedInputPollOptionMedia() }

func (v InputMediaAnimation) sealedInputPollOptionMedia() {}
func (v InputMediaLivePhoto) sealedInputPollOptionMedia() {}
func (v InputMediaLocation) sealedInputPollOptionMedia() {}
func (v InputMediaPhoto) sealedInputPollOptionMedia() {}
func (v InputMediaSticker) sealedInputPollOptionMedia() {}
func (v InputMediaVenue) sealedInputPollOptionMedia() {}
func (v InputMediaVideo) sealedInputPollOptionMedia() {}

func unmarshalInputPollOptionMedia(data []byte) (InputPollOptionMedia, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "animation":
		var v InputMediaAnimation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "live_photo":
		var v InputMediaLivePhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "location":
		var v InputMediaLocation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "photo":
		var v InputMediaPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "sticker":
		var v InputMediaSticker
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "venue":
		var v InputMediaVenue
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v InputMediaVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputPollOptionMedia: %q", disc.Key)
	}
}  
// This object describes the way a background is filled based on the selected
// colors. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#backgroundfill
//sumtype:decl
type BackgroundFill interface{ part; formJSON; sealedBackgroundFill() }

func (v BackgroundFillSolid) sealedBackgroundFill() {}
func (v BackgroundFillGradient) sealedBackgroundFill() {}
func (v BackgroundFillFreeformGradient) sealedBackgroundFill() {}

func unmarshalBackgroundFill(data []byte) (BackgroundFill, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "solid":
		var v BackgroundFillSolid
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "gradient":
		var v BackgroundFillGradient
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "freeform_gradient":
		var v BackgroundFillFreeformGradient
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown BackgroundFill: %q", disc.Key)
	}
}  
// This object describes the type of a background. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#backgroundtype
//sumtype:decl
type BackgroundType interface{ part; formJSON; sealedBackgroundType() }

func (v BackgroundTypeFill) sealedBackgroundType() {}
func (v BackgroundTypeWallpaper) sealedBackgroundType() {}
func (v BackgroundTypePattern) sealedBackgroundType() {}
func (v BackgroundTypeChatTheme) sealedBackgroundType() {}

func unmarshalBackgroundType(data []byte) (BackgroundType, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "fill":
		var v BackgroundTypeFill
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "wallpaper":
		var v BackgroundTypeWallpaper
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "pattern":
		var v BackgroundTypePattern
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat_theme":
		var v BackgroundTypeChatTheme
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown BackgroundType: %q", disc.Key)
	}
}  
// This object contains information about one member of a chat. Currently, the
// following 6 types of chat members are supported:
//
// See https://core.telegram.org/bots/api#chatmember
//sumtype:decl
type ChatMember interface{ part; formJSON; sealedChatMember() }

func (v ChatMemberOwner) sealedChatMember() {}
func (v ChatMemberAdministrator) sealedChatMember() {}
func (v ChatMemberMember) sealedChatMember() {}
func (v ChatMemberRestricted) sealedChatMember() {}
func (v ChatMemberLeft) sealedChatMember() {}
func (v ChatMemberBanned) sealedChatMember() {}

func unmarshalChatMember(data []byte) (ChatMember, error) {
	var disc struct {
		Key string `json:"status"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "creator":
		var v ChatMemberOwner
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "administrator":
		var v ChatMemberAdministrator
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "member":
		var v ChatMemberMember
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "restricted":
		var v ChatMemberRestricted
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "left":
		var v ChatMemberLeft
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "kicked":
		var v ChatMemberBanned
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown ChatMember: %q", disc.Key)
	}
}  
// Describes the type of a clickable area on a story. Currently, it can be one
// of
//
// See https://core.telegram.org/bots/api#storyareatype
//sumtype:decl
type StoryAreaType interface{ part; formJSON; sealedStoryAreaType() }

func (v StoryAreaTypeLocation) sealedStoryAreaType() {}
func (v StoryAreaTypeSuggestedReaction) sealedStoryAreaType() {}
func (v StoryAreaTypeLink) sealedStoryAreaType() {}
func (v StoryAreaTypeWeather) sealedStoryAreaType() {}
func (v StoryAreaTypeUniqueGift) sealedStoryAreaType() {}

func unmarshalStoryAreaType(data []byte) (StoryAreaType, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "location":
		var v StoryAreaTypeLocation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "suggested_reaction":
		var v StoryAreaTypeSuggestedReaction
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "link":
		var v StoryAreaTypeLink
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "weather":
		var v StoryAreaTypeWeather
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "unique_gift":
		var v StoryAreaTypeUniqueGift
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown StoryAreaType: %q", disc.Key)
	}
}  
// This object describes the type of a reaction. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#reactiontype
//sumtype:decl
type ReactionType interface{ part; formJSON; sealedReactionType() }

func (v ReactionTypeEmoji) sealedReactionType() {}
func (v ReactionTypeCustomEmoji) sealedReactionType() {}
func (v ReactionTypePaid) sealedReactionType() {}

func unmarshalReactionType(data []byte) (ReactionType, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "emoji":
		var v ReactionTypeEmoji
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "custom_emoji":
		var v ReactionTypeCustomEmoji
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "paid":
		var v ReactionTypePaid
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown ReactionType: %q", disc.Key)
	}
}  
// This object describes a gift received and owned by a user or a chat.
// Currently, it can be one of
//
// See https://core.telegram.org/bots/api#ownedgift
//sumtype:decl
type OwnedGift interface{ part; formJSON; sealedOwnedGift() }

func (v OwnedGiftRegular) sealedOwnedGift() {}
func (v OwnedGiftUnique) sealedOwnedGift() {}

func unmarshalOwnedGift(data []byte) (OwnedGift, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "regular":
		var v OwnedGiftRegular
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "unique":
		var v OwnedGiftUnique
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown OwnedGift: %q", disc.Key)
	}
}  
// This object represents the scope to which bot commands are applied.
// Currently, the following 7 scopes are supported:
//
// See https://core.telegram.org/bots/api#botcommandscope
//sumtype:decl
type BotCommandScope interface{ part; formJSON; sealedBotCommandScope() }

func (v BotCommandScopeDefault) sealedBotCommandScope() {}
func (v BotCommandScopeAllPrivateChats) sealedBotCommandScope() {}
func (v BotCommandScopeAllGroupChats) sealedBotCommandScope() {}
func (v BotCommandScopeAllChatAdministrators) sealedBotCommandScope() {}
func (v BotCommandScopeChat) sealedBotCommandScope() {}
func (v BotCommandScopeChatAdministrators) sealedBotCommandScope() {}
func (v BotCommandScopeChatMember) sealedBotCommandScope() {}

func unmarshalBotCommandScope(data []byte) (BotCommandScope, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "default":
		var v BotCommandScopeDefault
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "all_private_chats":
		var v BotCommandScopeAllPrivateChats
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "all_group_chats":
		var v BotCommandScopeAllGroupChats
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "all_chat_administrators":
		var v BotCommandScopeAllChatAdministrators
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat":
		var v BotCommandScopeChat
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat_administrators":
		var v BotCommandScopeChatAdministrators
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat_member":
		var v BotCommandScopeChatMember
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown BotCommandScope: %q", disc.Key)
	}
}  
// This object describes the bot's menu button in a private chat. It should be
// one of
//
// If a menu button other than MenuButtonDefault is set for a private chat, then
// it is applied in the chat. Otherwise the default menu button is applied. By
// default, the menu button opens the list of bot commands.
//
// See https://core.telegram.org/bots/api#menubutton
//sumtype:decl
type MenuButton interface{ part; formJSON; sealedMenuButton() }

func (v MenuButtonCommands) sealedMenuButton() {}
func (v MenuButtonWebApp) sealedMenuButton() {}
func (v MenuButtonDefault) sealedMenuButton() {}

func unmarshalMenuButton(data []byte) (MenuButton, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "commands":
		var v MenuButtonCommands
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "web_app":
		var v MenuButtonWebApp
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "default":
		var v MenuButtonDefault
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown MenuButton: %q", disc.Key)
	}
}  
// This object describes the source of a chat boost. It can be one of
//
// See https://core.telegram.org/bots/api#chatboostsource
//sumtype:decl
type ChatBoostSource interface{ part; formJSON; sealedChatBoostSource() }

func (v ChatBoostSourcePremium) sealedChatBoostSource() {}
func (v ChatBoostSourceGiftCode) sealedChatBoostSource() {}
func (v ChatBoostSourceGiveaway) sealedChatBoostSource() {}

func unmarshalChatBoostSource(data []byte) (ChatBoostSource, error) {
	var disc struct {
		Key string `json:"source"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "premium":
		var v ChatBoostSourcePremium
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "gift_code":
		var v ChatBoostSourceGiftCode
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "giveaway":
		var v ChatBoostSourceGiveaway
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown ChatBoostSource: %q", disc.Key)
	}
}  
// This object represents the content of a media message to be sent. It should
// be one of
//
// See https://core.telegram.org/bots/api#inputmedia
//sumtype:decl
type InputMedia interface{ part; formJSON; sealedInputMedia() }

func (v InputMediaAnimation) sealedInputMedia() {}
func (v InputMediaAudio) sealedInputMedia() {}
func (v InputMediaDocument) sealedInputMedia() {}
func (v InputMediaLivePhoto) sealedInputMedia() {}
func (v InputMediaPhoto) sealedInputMedia() {}
func (v InputMediaVideo) sealedInputMedia() {}

func unmarshalInputMedia(data []byte) (InputMedia, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "animation":
		var v InputMediaAnimation
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "audio":
		var v InputMediaAudio
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "document":
		var v InputMediaDocument
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "live_photo":
		var v InputMediaLivePhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "photo":
		var v InputMediaPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v InputMediaVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputMedia: %q", disc.Key)
	}
}  
// This object describes the paid media to be sent. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#inputpaidmedia
//sumtype:decl
type InputPaidMedia interface{ part; formJSON; sealedInputPaidMedia() }

func (v InputPaidMediaLivePhoto) sealedInputPaidMedia() {}
func (v InputPaidMediaPhoto) sealedInputPaidMedia() {}
func (v InputPaidMediaVideo) sealedInputPaidMedia() {}

func unmarshalInputPaidMedia(data []byte) (InputPaidMedia, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "live_photo":
		var v InputPaidMediaLivePhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "photo":
		var v InputPaidMediaPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v InputPaidMediaVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputPaidMedia: %q", disc.Key)
	}
}  
// This object describes a profile photo to set. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#inputprofilephoto
//sumtype:decl
type InputProfilePhoto interface{ part; formJSON; sealedInputProfilePhoto() }

func (v InputProfilePhotoStatic) sealedInputProfilePhoto() {}
func (v InputProfilePhotoAnimated) sealedInputProfilePhoto() {}

func unmarshalInputProfilePhoto(data []byte) (InputProfilePhoto, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "static":
		var v InputProfilePhotoStatic
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "animated":
		var v InputProfilePhotoAnimated
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputProfilePhoto: %q", disc.Key)
	}
}  
// This object describes the content of a story to post. Currently, it can be
// one of
//
// See https://core.telegram.org/bots/api#inputstorycontent
//sumtype:decl
type InputStoryContent interface{ part; formJSON; sealedInputStoryContent() }

func (v InputStoryContentPhoto) sealedInputStoryContent() {}
func (v InputStoryContentVideo) sealedInputStoryContent() {}

func unmarshalInputStoryContent(data []byte) (InputStoryContent, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "photo":
		var v InputStoryContentPhoto
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "video":
		var v InputStoryContentVideo
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown InputStoryContent: %q", disc.Key)
	}
}  
// This object describes the state of a revenue withdrawal operation. Currently,
// it can be one of
//
// See https://core.telegram.org/bots/api#revenuewithdrawalstate
//sumtype:decl
type RevenueWithdrawalState interface{ part; formJSON; sealedRevenueWithdrawalState() }

func (v RevenueWithdrawalStatePending) sealedRevenueWithdrawalState() {}
func (v RevenueWithdrawalStateSucceeded) sealedRevenueWithdrawalState() {}
func (v RevenueWithdrawalStateFailed) sealedRevenueWithdrawalState() {}

func unmarshalRevenueWithdrawalState(data []byte) (RevenueWithdrawalState, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "pending":
		var v RevenueWithdrawalStatePending
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "succeeded":
		var v RevenueWithdrawalStateSucceeded
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "failed":
		var v RevenueWithdrawalStateFailed
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown RevenueWithdrawalState: %q", disc.Key)
	}
}  
// This object describes the source of a transaction, or its recipient for
// outgoing transactions. Currently, it can be one of
//
// See https://core.telegram.org/bots/api#transactionpartner
//sumtype:decl
type TransactionPartner interface{ part; formJSON; sealedTransactionPartner() }

func (v TransactionPartnerUser) sealedTransactionPartner() {}
func (v TransactionPartnerChat) sealedTransactionPartner() {}
func (v TransactionPartnerAffiliateProgram) sealedTransactionPartner() {}
func (v TransactionPartnerFragment) sealedTransactionPartner() {}
func (v TransactionPartnerTelegramAds) sealedTransactionPartner() {}
func (v TransactionPartnerTelegramAPI) sealedTransactionPartner() {}
func (v TransactionPartnerOther) sealedTransactionPartner() {}

func unmarshalTransactionPartner(data []byte) (TransactionPartner, error) {
	var disc struct {
		Key string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "user":
		var v TransactionPartnerUser
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "chat":
		var v TransactionPartnerChat
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "affiliate_program":
		var v TransactionPartnerAffiliateProgram
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "fragment":
		var v TransactionPartnerFragment
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "telegram_ads":
		var v TransactionPartnerTelegramAds
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "telegram_api":
		var v TransactionPartnerTelegramAPI
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "other":
		var v TransactionPartnerOther
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown TransactionPartner: %q", disc.Key)
	}
}  
// This object represents an error in the Telegram Passport element which was
// submitted that should be resolved by the user. It should be one of:
//
// See https://core.telegram.org/bots/api#passportelementerror
//sumtype:decl
type PassportElementError interface{ part; formJSON; sealedPassportElementError() }

func (v PassportElementErrorDataField) sealedPassportElementError() {}
func (v PassportElementErrorFrontSide) sealedPassportElementError() {}
func (v PassportElementErrorReverseSide) sealedPassportElementError() {}
func (v PassportElementErrorSelfie) sealedPassportElementError() {}
func (v PassportElementErrorFile) sealedPassportElementError() {}
func (v PassportElementErrorFiles) sealedPassportElementError() {}
func (v PassportElementErrorTranslationFile) sealedPassportElementError() {}
func (v PassportElementErrorTranslationFiles) sealedPassportElementError() {}
func (v PassportElementErrorUnspecified) sealedPassportElementError() {}

func unmarshalPassportElementError(data []byte) (PassportElementError, error) {
	var disc struct {
		Key string `json:"source"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Key {
	case "data":
		var v PassportElementErrorDataField
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "front_side":
		var v PassportElementErrorFrontSide
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "reverse_side":
		var v PassportElementErrorReverseSide
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "selfie":
		var v PassportElementErrorSelfie
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "file":
		var v PassportElementErrorFile
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "files":
		var v PassportElementErrorFiles
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "translation_file":
		var v PassportElementErrorTranslationFile
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "translation_files":
		var v PassportElementErrorTranslationFiles
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	case "unspecified":
		var v PassportElementErrorUnspecified
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, err
		}
		return v, nil
	default:
		return nil, fmt.Errorf("unknown PassportElementError: %q", disc.Key)
	}
}

// MaybeMessage represents a method return value that is either an edited
// Message or True for inline messages.
//
//sumtype:decl
type MaybeMessage interface{ sealedMaybeMessage() }

func (v Message) sealedMaybeMessage() {}
func (v True) sealedMaybeMessage()    {}

func unmarshalMaybeMessage(data []byte) (MaybeMessage, error) {
	{
		var v Message
		if json.Unmarshal(data, &v) == nil {
			return v, nil
		}
	}
	{
		var v True
		if json.Unmarshal(data, &v) == nil {
			return v, nil
		}
	}
	return nil, fmt.Errorf(
		"cannot unmarshal %q into any of the MaybeMessage variants",
		string(data),
	)
}

// ChatID represents a chat identifier, either a numeric ID or a username.
//
//sumtype:decl
type ChatID interface{ part; sealedChatID() }

func (v ID) sealedChatID()       {}
func (v Username) sealedChatID() {}

func unmarshalChatID(data []byte) (ChatID, error) {
	return nil, nil
}

// InputFile represents a file to send, either by file ID or by uploading.
//
//sumtype:decl
type InputFile interface {
    part
    attach(p *multipartPayload) (string, error)
    sealedInputFile()
}

func (v FileID) sealedInputFile() {}
func (v Upload) sealedInputFile() {}

func unmarshalInputFile(data []byte) (InputFile, error) {
	return nil, nil
}

// ReplyMarkup represents a reply markup attached to a message.
//
//sumtype:decl
type ReplyMarkup interface{ part; formJSON; sealedReplyMarkup() }

func (v InlineKeyboardMarkup) sealedReplyMarkup() {}
func (v ReplyKeyboardMarkup) sealedReplyMarkup()  {}
func (v ReplyKeyboardRemove) sealedReplyMarkup()  {}
func (v ForceReply) sealedReplyMarkup()           {}

func unmarshalReplyMarkup(data []byte) (ReplyMarkup, error) {
	return nil, nil
}

// InputMediaGroup represents a media element in a media group.
//
//sumtype:decl
type InputMediaGroup interface{ part; formJSON; sealedInputMediaGroup() }

func (v InputMediaAudio) sealedInputMediaGroup()     {}
func (v InputMediaDocument) sealedInputMediaGroup()  {}
func (v InputMediaLivePhoto) sealedInputMediaGroup() {}
func (v InputMediaPhoto) sealedInputMediaGroup()     {}
func (v InputMediaVideo) sealedInputMediaGroup()     {}

func unmarshalInputMediaGroup(data []byte) (InputMediaGroup, error) {
	return nil, nil
}

// This object represents the content of a message to be sent as a result of an
// inline query.
//
// See https://core.telegram.org/bots/api#inputmessagecontent
//sumtype:decl
type InputMessageContent interface{ part; formJSON; sealedInputMessageContent() }

func (v InputInvoiceMessageContent) sealedInputMessageContent()  {}
func (v InputVenueMessageContent) sealedInputMessageContent()    {}
func (v InputLocationMessageContent) sealedInputMessageContent() {}
func (v InputContactMessageContent) sealedInputMessageContent()  {}
func (v InputTextMessageContent) sealedInputMessageContent()     {}

func unmarshalInputMessageContent(data []byte) (InputMessageContent, error) {
	return nil, nil
}

// This object describes a message that can be inaccessible to the bot.
//
// See https://core.telegram.org/bots/api#maybeinaccessiblemessage
//sumtype:decl
type MaybeInaccessibleMessage interface{ sealedMaybeInaccessibleMessage() }

func (v Message) sealedMaybeInaccessibleMessage()             {}
func (v InaccessibleMessage) sealedMaybeInaccessibleMessage() {}

func unmarshalMaybeInaccessibleMessage(data []byte) (MaybeInaccessibleMessage, error) {
	var disc struct {
		Key int64 `json:"date"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, fmt.Errorf("unmarshaling discriminator for MaybeInaccessibleMessage: %w", err)
	}
	switch disc.Key {
	case 0:
		var v InaccessibleMessage
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, fmt.Errorf("unmarshaling InaccessibleMessage: %w", err)
		}
		return v, nil
	default:
		var v Message
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, fmt.Errorf("unmarshaling Message: %w", err)
		}
		return v, nil
	}
}

// This object represents one result of an inline query.
//
// Note: All URLs passed in inline query results will be available to end users
// and therefore must be assumed to be public.
//
// See https://core.telegram.org/bots/api#inlinequeryresult
//sumtype:decl
type InlineQueryResult interface{ part; formJSON; sealedInlineQueryResult() }

func (v InlineQueryResultCachedAudio) sealedInlineQueryResult()    {}
func (v InlineQueryResultCachedDocument) sealedInlineQueryResult() {}
func (v InlineQueryResultCachedGif) sealedInlineQueryResult()      {}
func (v InlineQueryResultCachedMpeg4Gif) sealedInlineQueryResult() {}
func (v InlineQueryResultCachedPhoto) sealedInlineQueryResult()    {}
func (v InlineQueryResultCachedSticker) sealedInlineQueryResult()  {}
func (v InlineQueryResultCachedVideo) sealedInlineQueryResult()    {}
func (v InlineQueryResultCachedVoice) sealedInlineQueryResult()    {}
func (v InlineQueryResultArticle) sealedInlineQueryResult()        {}
func (v InlineQueryResultAudio) sealedInlineQueryResult()          {}
func (v InlineQueryResultContact) sealedInlineQueryResult()        {}
func (v InlineQueryResultGame) sealedInlineQueryResult()           {}
func (v InlineQueryResultDocument) sealedInlineQueryResult()       {}
func (v InlineQueryResultGif) sealedInlineQueryResult()            {}
func (v InlineQueryResultLocation) sealedInlineQueryResult()       {}
func (v InlineQueryResultMpeg4Gif) sealedInlineQueryResult()       {}
func (v InlineQueryResultPhoto) sealedInlineQueryResult()          {}
func (v InlineQueryResultVenue) sealedInlineQueryResult()          {}
func (v InlineQueryResultVideo) sealedInlineQueryResult()          {}
func (v InlineQueryResultVoice) sealedInlineQueryResult()          {}