# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
name: govulncheck
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '17 3 * * *'
jobs:
  govulncheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db  # v3.6.3
        with:
          version: v2026.3.9
      - run: task vuln:sarif
      - uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8  # v4.33.0
        with:
          sarif_file: govulncheck.sarif
