# SPDX-FileCopyrightText: 2026 Andrey Chernykh
# SPDX-License-Identifier: MIT
name: release
'on':
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151  # v4.0.1
        with:
          version: v2026.4.14
      - run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
